### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email":"yadnyesh1@gmail.com",
  "password":"123456"
}

###

### Create Journal
POST http://localhost:8080/api/journals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YWRueWVzaDFAZ21haWwuY29tIiwiaWF0IjoxNzgyOTEwNzQyLCJleHAiOjE3ODI5OTcxNDJ9.fiOqeCw_fpDPOazIBZK5gEuHo0MKvlEWqmkPsAPegwM
Content-Type: application/json

{
  "title":"Day 1",
  "content":"Today I completed my LifeOS backend."
}

###

### Get All Journals
GET http://localhost:8080/api/journals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YWRueWVzaDFAZ21haWwuY29tIiwiaWF0IjoxNzgyNzI5MzI3LCJleHAiOjE3ODI4MTU3Mjd9.b4M2V2avtoCZXQUFkgn0GqI6XGOSocFmM22aU_3ayAM

###

### Get Journal By ID
GET http://localhost:8080/api/journals/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YWRueWVzaDFAZ21haWwuY29tIiwiaWF0IjoxNzgyNzI5MzI3LCJleHAiOjE3ODI4MTU3Mjd9.b4M2V2avtoCZXQUFkgn0GqI6XGOSocFmM22aU_3ayAM

###

### Update Journal
PUT http://localhost:8080/api/journals/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YWRueWVzaDFAZ21haWwuY29tIiwiaWF0IjoxNzgyNzI5MzI3LCJleHAiOjE3ODI4MTU3Mjd9.b4M2V2avtoCZXQUFkgn0GqI6XGOSocFmM22aU_3ayAM
Content-Type: application/json

{
  "title":"Updated Journal",
  "content":"Today I completed the Journal module."
}

###

### Delete Journal
DELETE http://localhost:8080/api/journals/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YWRueWVzaDFAZ21haWwuY29tIiwiaWF0IjoxNzgyNzI5MzI3LCJleHAiOjE3ODI4MTU3Mjd9.b4M2V2avtoCZXQUFkgn0GqI6XGOSocFmM22aU_3ayAM