#################################################
# APPLICATION
#################################################

spring.application.name=LifeOS

#################################################
# SERVER
#################################################

server.port=8081

#################################################
# POSTGRESQL DATABASE
#################################################

spring.datasource.url=jdbc:postgresql://localhost:5432/lifeos_db
spring.datasource.username=postgres
spring.datasource.password=Yadnyesh2906#

spring.datasource.driver-class-name=org.postgresql.Driver

#################################################
# JPA / HIBERNATE
#################################################

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#################################################
# LOGGING
#################################################

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE